import { Market, Position } from './types';

export const markets: Market[] = [
  {
    id: '1',
    title: 'Taxa Selic ao final de 2025',
    description: 'Qual será a meta da taxa Selic definida pelo Copom na última reunião de 2025?',
    category: 'Juros',
    variable: 'Taxa Selic',
    unit: '% a.a.',
    lowerBound: 10.0,
    upperBound: 15.0,
    resolutionDate: '2025-12-18',
    settlementSource: 'Banco Central do Brasil — Ata do Copom',
    status: 'active',
    currentPrice: 0.62,
    volume24h: 284_700,
    totalVolume: 3_420_000,
    createdAt: '2025-01-15',
  },
  {
    id: '2',
    title: 'IPCA acumulado 12 meses — Junho 2025',
    description: 'Qual será o IPCA acumulado em 12 meses divulgado pelo IBGE referente a junho de 2025?',
    category: 'Inflação',
    variable: 'IPCA 12m',
    unit: '%',
    lowerBound: 3.0,
    upperBound: 7.0,
    resolutionDate: '2025-07-10',
    settlementSource: 'IBGE — Sistema Nacional de Índices de Preços ao Consumidor',
    status: 'active',
    currentPrice: 0.45,
    volume24h: 156_200,
    totalVolume: 2_180_000,
    createdAt: '2025-02-01',
  },
  {
    id: '3',
    title: 'Dólar PTAX final de março 2026',
    description: 'Qual será a cotação de venda do dólar PTAX no último dia útil de março de 2026?',
    category: 'Câmbio',
    variable: 'USD/BRL PTAX',
    unit: 'R$',
    lowerBound: 5.00,
    upperBound: 7.00,
    resolutionDate: '2026-03-31',
    settlementSource: 'Banco Central do Brasil — PTAX',
    status: 'active',
    currentPrice: 0.55,
    volume24h: 412_000,
    totalVolume: 5_800_000,
    createdAt: '2025-03-01',
  },
  {
    id: '4',
    title: 'PIB Brasil 2025 — Variação anual',
    description: 'Qual será a variação real do PIB brasileiro em 2025 divulgada pelo IBGE?',
    category: 'Atividade',
    variable: 'PIB real',
    unit: '%',
    lowerBound: 0.0,
    upperBound: 4.0,
    resolutionDate: '2026-03-07',
    settlementSource: 'IBGE — Contas Nacionais Trimestrais',
    status: 'active',
    currentPrice: 0.52,
    volume24h: 98_500,
    totalVolume: 1_450_000,
    createdAt: '2025-01-20',
  },
  {
    id: '5',
    title: 'Taxa de desemprego — Dez 2024',
    description: 'Qual foi a taxa de desocupação divulgada pela PNAD Contínua referente ao trimestre encerrado em dezembro de 2024?',
    category: 'Emprego',
    variable: 'Desemprego PNAD',
    unit: '%',
    lowerBound: 5.0,
    upperBound: 9.0,
    resolutionDate: '2025-01-31',
    settlementSource: 'IBGE — PNAD Contínua',
    status: 'resolved',
    currentPrice: 0.38,
    volume24h: 0,
    totalVolume: 1_870_000,
    resolvedValue: 6.5,
    createdAt: '2024-10-01',
  },
  {
    id: '6',
    title: 'Ibovespa no final de 2025',
    description: 'Qual será o valor de fechamento do Ibovespa no último pregão de 2025?',
    category: 'Bolsa',
    variable: 'Ibovespa',
    unit: 'pontos',
    lowerBound: 100_000,
    upperBound: 160_000,
    resolutionDate: '2025-12-30',
    settlementSource: 'B3 — Cotação de fechamento oficial',
    status: 'active',
    currentPrice: 0.58,
    volume24h: 523_000,
    totalVolume: 7_200_000,
    createdAt: '2025-01-02',
  },
];

export const positions: Position[] = [
  {
    id: 'p1',
    marketId: '1',
    market: markets[0],
    side: 'long',
    quantity: 100,
    entryPrice: 0.55,
    currentPrice: 0.62,
    pnl: 7.0,
    pnlPercent: 12.7,
    timestamp: '2025-02-10',
  },
  {
    id: 'p2',
    marketId: '3',
    market: markets[2],
    side: 'long',
    quantity: 200,
    entryPrice: 0.48,
    currentPrice: 0.55,
    pnl: 14.0,
    pnlPercent: 14.6,
    timestamp: '2025-03-05',
  },
  {
    id: 'p3',
    marketId: '6',
    market: markets[5],
    side: 'short',
    quantity: 50,
    entryPrice: 0.65,
    currentPrice: 0.58,
    pnl: 3.5,
    pnlPercent: 10.8,
    timestamp: '2025-02-20',
  },
];

export const categories = ['Todos', 'Juros', 'Inflação', 'Câmbio', 'Atividade', 'Emprego', 'Bolsa'];
